// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEIFBH2vHJJhxMpKp-dJRZEwWc6vuXo0',
    appId: '1:333024348549:web:69473762d7ab48b870dcec',
    messagingSenderId: '333024348549',
    projectId: 'auth-15f15',
    authDomain: 'auth-15f15.firebaseapp.com',
    storageBucket: 'auth-15f15.firebasestorage.app',
    measurementId: 'G-E5HGBKJELX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-EzXxgkztaHKz7dYBaTtwUSPttCnvSos',
    appId: '1:333024348549:android:fb07bd84fe3b85d470dcec',
    messagingSenderId: '333024348549',
    projectId: 'auth-15f15',
    storageBucket: 'auth-15f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXky94YxoRFSi34aGLK3Ytf-Ka_7bk_i0',
    appId: '1:333024348549:ios:0249810eebb56a2c70dcec',
    messagingSenderId: '333024348549',
    projectId: 'auth-15f15',
    storageBucket: 'auth-15f15.firebasestorage.app',
    iosBundleId: 'com.example.rentHiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEIFBH2vHJJhxMpKp-dJRZEwWc6vuXo0',
    appId: '1:333024348549:web:69473762d7ab48b870dcec',
    messagingSenderId: '333024348549',
    projectId: 'auth-15f15',
    authDomain: 'auth-15f15.firebaseapp.com',
    storageBucket: 'auth-15f15.firebasestorage.app',
    measurementId: 'G-E5HGBKJELX',
  );
}